trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: subscriptionId
    value: 6eeb26c2-d05d-430f-81c2-5510705013f6
  - name: infraProject
    value: $(Build.SourcesDirectory)/deployments/Softville.Prospecting.Infra
  - name: infraProjectTf
    value: $(Build.SourcesDirectory)/deployments/Softville.Prospecting.Infra/cdktf.out/stacks/MyAzureInfrastructure

steps:
  - task: Npm@1
    displayName: 'cdktf install'
    inputs:
      command: custom
      customCommand: install --global cdktf-cli@latest
      workingDir: $(infraProject)

  - task: Npm@1
    displayName: 'AzureRM provider for cdktf install'
    inputs:
      command: custom
      customCommand: install @cdktf/provider-azurerm
      workingDir: $(infraProject)

  - task: AzureCLI@2
    displayName: 'cdktf deploy'
    inputs:
      workingDirectory: $(infraProject)
      azureSubscription: 'sc-prspct-test-plc-001-2'
      addSpnToEnvironment: true
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |

        $env:ARM_USE_MSI='true'
        $env:ARM_TENANT_ID=$env:tenantId
        $env:ARM_SUBSCRIPTION_ID=$env:SUBSCRIPTIONID
        
        gci env: -Recurse

        cdktf deploy --auto-approve
