trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: infraProject
    value: $(Build.SourcesDirectory)/deployments/Softville.Prospecting.Infra
  - name: infraProjectTf
    value: $(Build.SourcesDirectory)/deployments/Softville.Prospecting.Infra/cdktf.out/stacks/MyAzureInfrastructure

steps:
  - task: Npm@1
    displayName: 'cdktf install'
    inputs:
      command: custom
      customCommand: install --global cdktf-cli@latest
      workingDir: $(infraProject)

  - task: Npm@1
    displayName: 'AzureRM provider for cdktf install'
    inputs:
      command: custom
      customCommand: install @cdktf/provider-azurerm
      workingDir: $(infraProject)

  - task: AzureCLI@2
    displayName: 'cdktf deploy'
    inputs:
      workingDirectory: $(infraProject)
      azureSubscription: 'sc-prspct-test-plc-001-2'
      addSpnToEnvironment: true
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        cdktf deploy --auto-approve
